[project]
name = "ftrack-processor"
version = "1.4.9"
description = ""
authors = [{name = "Ynput s.r.o.", email ="info@ynput.io"}]
dependencies = [
    "platformdirs",
    "ayon-python-api==1.2.2",
    "ftrack-python-api==2.3.3"
]

[tool.setuptools]
py-modules = ["processor", "ftrack_common"]
