[project]
name = "ftrack-leecher"
version = "1.4.14+dev"
description = ""
authors = [{name = "Ynput s.r.o.", email ="info@ynput.io"}]
dependencies = [
    "ayon-python-api==1.2.9",
    "ftrack-python-api==2.3.3"
]
