[project]
name = "ftrack-transmitter"
version = "1.4.14"
description = ""
authors = [{name = "Ynput s.r.o.", email ="info@ynput.io"}]
dependencies = [
    "ayon-python-api==1.2.9",
    "ftrack-python-api==2.3.3"
]

[tool.setuptools]
py-modules = ["transmitter", "ftrack_common"]
